### ISSUE TITLE
Don't try to backup saves if game platform is not PC

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi-playnite#2]
Since ludusavi is made and intended for PC games, games from other platforms should be skipped.

![imagen](https://user-images.githubusercontent.com/1389286/88886628-80be2780-d200-11ea-93c8-286965c0b4aa.png)

**Comment by mtkennerly** [comment]
I can make it configurable whether to ask for such games, but we wouldn't want to disable it completely because you can actually create a custom entry in Ludusavi with the same name if you want to back it up (e.g., pointing to an emulator save file).

**Comment by darklinkpower** [comment]
That would help a lot actually. This makes me think of a few things:

1. Since Ludusavi uses game names to generate the base directory of the save backup, it could potentially lead to issues in cases like this where games from different platforms have the same name:

![imagen](https://user-images.githubusercontent.com/1389286/88929441-bafae980-d23f-11ea-8f8d-d2aae09fed57.png)

That could be solved by maybe using "GameName" + "Platform" to generate the base64 name in Playnite's side but I don't know how it could be handled in the standalone Ludusavi since it won't recognize the game platform. Another idea would be to use "GameName" + "File extension", although that could be useless for zipped files. Still, there could be cases where this too could be an issue on PC, for example: Doom (1993) and Doom (2016)

2. Perhaps it would be worth considering using a built in feature to configure the save file for emulated games as a function in Playnite using the [Dialogs Factory](https://playnite.link/docs/api/Playnite.SDK.IDialogsFactory.html#Playnite_SDK_IDialogsFactory_SelectFile_System_String_)

**Comment by mtkennerly** [comment]
Oh, that's a good point. I think `Name (Platform)` would work, as long as it's configurable whether to add the suffix - probably off by default to keep it simple. Then you can decide in the Ludusavi config whether you want to define your custom games with a suffix or not:

> ![image](https://user-images.githubusercontent.com/4934192/88935864-349ad380-d250-11ea-8a42-9fa592028e4d.png)

Or maybe try both (like how the Steam ID fallback works) and make it configurable whether to prioritize the version with or without the suffix. That way, you don't run into a situation where you haven't been using suffixes, then oops you realize you need it for a new game, and now you have to go back and add it for everything else.

Incidentally, the manifest uses the exact names `Doom (1993)` and `Doom (2016)` already :D That's because PCGW uses the same names for its articles on them.

I think in-Playnite configuration of Ludusavi would be interesting, but I'm not sure if the dialog options are customizable enough. I'm imagining something like:

* Get a notification that no data was found
* Click the notification to add a config
* Show a screen for entering the name, multiple files/folders, and multiple registry keys

I only see dialogs for entering a single string or selecting a single file/folder. Not sure if there's a way to do a full custom modal window. Maybe clicking the notification could open Ludusavi directly to the custom games screen? That seems like a nice compromise.

**Comment by mtkennerly** [comment]
![image](https://user-images.githubusercontent.com/4934192/89146241-2505de00-d521-11ea-95ad-d808f632905d.png)
