### ISSUE TITLE
Save multiple backups on an interval

### ISSUE THREAD

**Issue by ANRCorleone** [mtkennerly/ludusavi-playnite#24]
Hello @mtkennerly 

I've started implementing this little addition. Plan is to use a symbolic link to the backup copy that ludusavi creates, then keep copying from that link while in-game so it doesn't collide with the files the game currently uses. When out of the game, that is when we enable a restore of a copy. The copy then overrides what you have there that ludusavi looks for. 

I hope I don't get too many hiccups and that no one has been implementing this yet :).

Cheers!

**Comment by mtkennerly** [comment]
Hi! Sorry for the very late reply, but here's my input on this one:

* For the aspect of managing multiple copies of backups per game, that should rely on [mtkennerly/ludusavi#74](https://github.com/mtkennerly/ludusavi/issues/74), rather than implementing it in the plugin itself. That way, you get consistent behavior in Ludusavi, the Playnite plugin, and in any other future plugins.
* Once that's done, then adding a timer for backups during play would be great.

**Comment by mtkennerly** [comment]
@ANRCorleone This is (finally) available now in v0.10.0 of the plugin.

Are there any other changes from the AutoSave fork that you think should be merged back here, or would it be safe to retire now?

**Comment by ANRCorleone** [comment]
Hello @mtkennerly sorry for the late reply, been busy with work. I quickly tested the ludusavi playnite plugin and I can't find option to pick an item from multiple backups that are generated automatically and restore one from there (like pick a backup from 3 hours ago, etc.). It was what I added on that fork, is that option available in ludusavi playnite now?

**Comment by mtkennerly** [comment]
No worries! Yes, I did add that, but it requires Ludusavi 0.12.0 or newer, so that might be why you didn't see it.

> <img width="837" alt="image" src="https://user-images.githubusercontent.com/4934192/189622218-3300df7f-9256-4857-9362-b435897a4c6b.png">

If the extension can't get the list of backups (because you have an older Ludusavi, or the game just doesn't have any backups, or it does but the name doesn't match between Playnite and Ludusavi), then it will just show the original restore option without the extra menu level.

**Comment by ANRCorleone** [comment]
Thank you 😸 I'll archive that repo now then

**Comment by mtkennerly** [comment]
Thanks!

Do you think it would be a good idea to make a new release of AutoSave so that the plugin status is also visible in Playnite? If you're just browsing in Playnite, you won't know that it's archived. Could update the notes shown in the plugin browser (below) and maybe even log a warning on startup.

> <img width="523" alt="image" src="https://user-images.githubusercontent.com/4934192/190010962-f751a8fa-dded-47e4-9a27-c07026840f65.png">

**Comment by ANRCorleone** [comment]
All done 👍
