### ISSUE TITLE
default path inconsistency

### ISSUE THREAD

**Issue by Lacro59** [mtkennerly/ludusavi-playnite#4]
I keep the default paths.
The plugin run correctly if I put the Ludusavi application in C:/Users/<YOUR_NAME>/AppData/Local/Playnite.
And, for information, the directory for storing backups is in C:/Users/<YOUR_NAME>/ludusavi-playnite

By consequent, the configuration procedure is false for installation of Ludusavi application.

For a portable using and user friendly, it's best to have all in Playnite directory by default.

Hope to be clear, lol.
Sorry for my bad writing.

**Comment by mtkennerly** [comment]
No worries :)

You can already change the plugin settings to back up into the Playnite directory, if you prefer. But I'm not sure that it should be the default behavior. I think it could lead to some problems:

* If you uninstall/reinstall Playnite, you might accidentally delete the save backups (even though you could still use them with Ludusavi on its own outside of Playnite).
* If you use Playnite in portable mode and run it from a flash drive, your flash drive might get too full because of how many backups you have.
* The extension can go to different places depending on how you install it, so it could be harder to figure out where your backups actually are. On my system:

  * Installing with the zip file goes to: `C:\Users\mtken\AppData\Local\Playnite\Extensions`
  * Installing with the pext file goes to: `C:\Users\mtken\AppData\Roaming\Playnite\Extensions`

  I think, even if you uninstall the plugin from one method and reinstall it with the other method, it should still be able to find your saves.
