### ISSUE TITLE
Right click menu items missing when only single game game is selected

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi-playnite#40]
Right click menu items missing when only single game game is selected

Single game (missing);
![image](https://user-images.githubusercontent.com/1389286/189474421-fcf5ae63-2351-4419-baa1-c5d4083fa6c3.png)

Multiple games (menu items show):
![image](https://user-images.githubusercontent.com/1389286/189474441-a58a3abe-25b4-49cb-b63a-98cce0577c3d.png)

**Comment by mtkennerly** [comment]
Do you have any other extensions that might be impacting this, or is there anything in the log indicating an error? It works on my end:

> <img width="795" alt="image" src="https://user-images.githubusercontent.com/4934192/189475855-0a92c6e5-f96a-4292-b484-69dc2a9f1586.png">

**Comment by darklinkpower** [comment]
There were no errors but I just uninstalled and reinstalled the extension and for some reason it shows now

![image](https://user-images.githubusercontent.com/1389286/189484640-f52ab7fa-744f-41d8-a7c7-decd39a688f0.png)

This makes me think that this is possibly an issue in Playnite itself rather than the extension. I'll be checking and let you know if I find anything

**Comment by hunkyburrito** [comment]
This has also been happening to me, but the reinstall did not fix it

**Comment by mtkennerly** [comment]
Thanks for the extra info. Apparently, member dictionaries default to null rather than empty, so when you open the context menu and it tries to check the multi-backup info, it could still be null. This would happen with older Ludusavi versions (since they don't support multi-backup) or potentially if you opened the context menu really fast (before it finished retrieving the multi-backup info). This should be fixed in 0.10.2 shortly.

**Comment by darklinkpower** [comment]
That's correct, you need to initialize the dictionaries. I wonder why I missed any error in the logs, sorry about that and thanks for the fix 👍
