### ISSUE TITLE
"Look up with another title" behaves as if choosing an existing custom entry

### ISSUE THREAD

**Issue by WildGenius** [mtkennerly/ludusavi-playnite#61]
Previously, entering the alternate game title searched and found the game, after which it was automatically backed up. Now, it just shows the existing Ludusavi custom entries, and searching for the alternate title does nothing.

**Comment by mtkennerly** [comment]
Hi! I think this may have to do with an issue recently where an invalid manifest was published for a few hours. I'm preparing a fix for Ludusavi so that it can automatically recover from that kind of error, but right now, it may need a manual step.

Could you try this?

* Delete `%APPDATA%\ludusavi\manifest.yaml`
* Launch Ludusavi and wait for the "updating manifest" message to go away
* Try in Playnite again

**Comment by WildGenius** [comment]
Yup, that works! In case it matters, I'm using the portable version via creating a `ludusavi.portable` file along the exe. For some reason, yesterday deleting the manifest and redownloading didn't fix it, but today it did. Also in case it matters, Playnite was closed while deleting and redownloading the ludusavi manifest.
