### ISSUE TITLE
Multi Person Save files

### ISSUE THREAD

**Issue by aweawe123za** [mtkennerly/ludusavi-playnite#63]
I guess this is a bit of a weird request. 

Is there any possibility that we could get a feature allowing multi person saving?
For example. 
A quick access button on the Playnite interface where you can choose the user that is playing. Automatically, switching the current save files for the correct users save files. 

I know this is a bit niche, but for people that have multiple gamers on 1 PC, this would be most convenient solution.

**Comment by mtkennerly** [comment]
From what I understand, there aren't any plans for Playnite itself to have profile functionality, since it expects you to use multiple OS accounts (or portable installs), so I think adding a profile system here might end up having to fight against Playnite's design, unfortunately.

Both Playnite and Ludusavi can either store settings in the OS user folder or along with a portable install of each app, so that would be the simplest solution. If you turn on automatic restore-before-play and backup-after-play in Playnite, then it should just work after the players log into their account (or launch their portable copy of Playnite with a custom Ludusavi backup path).
