### ISSUE TITLE
can't set ludusavi up

### ISSUE THREAD

**Issue by Crasthiff** [mtkennerly/ludusavi-playnite#81]
The thing is, playnite won't show the ludusavi plugin settings... any help?
![image](https://github.com/user-attachments/assets/1316f3a2-c487-494e-8df4-dc60f6417a46)

**Comment by mtkennerly** [comment]
Hi! Just to confirm, in the `installed > generic` section, is Ludusavi listed as installed and enabled?

**Comment by Crasthiff** [comment]
> Hi! Just to confirm, in the `installed > generic` section, is Ludusavi listed as installed and enabled?

![image](https://github.com/user-attachments/assets/2ce9563c-4c06-48c8-8fee-d7272e5dcd1c)

this is how it is listed

**Comment by mtkennerly** [comment]
Hmm, I haven't seen that "extension failed to load properly" message before. Could you please send me a few files for troubleshooting?

* `%APPDATA%/Playnite/playnite.log`
* `%APPDATA%/Playnite/extensions.log`
* `%APPDATA%/Playnite/ExtensionsData/72e2de43-d859-44d8-914e-4277741c8208/config.json`

**Comment by Crasthiff** [comment]
[playnite.log](https://github.com/user-attachments/files/16739063/playnite.log)
[extensions.log](https://github.com/user-attachments/files/16739064/extensions.log)
[config.json](https://github.com/user-attachments/files/16739066/config.json)

**Comment by mtkennerly** [comment]
Somehow, your config.json got into a bad state, but I'm not sure how. The issue is that the paths, like `D:\Programas\Ludusavi\ludusavi.exe`, should have the backslashes escaped, as in `D:\\Programas\\Ludusavi\\ludusavi.exe`. Normally, when you edit the paths in Playnite, they get written with the escapes in the config file automatically, so I'm not sure why they didn't in this case. Did you edit the file manually, by any chance?

To  fix it, you can replace your config.json with this one, and it should start working: [config.json](https://github.com/user-attachments/files/16742328/config.json)

**Comment by Crasthiff** [comment]
you genius, all fixed!!!! thank you so much for taking the time to help a fellow gamer ♥
althoug is weird how this happened, bc it was all clean install, even my windows, i just formatted my pc due to an error during a mainteinance (and i hadn't formatted it in like 3 years), and no manual setting on path either, it auto set by opening playnite with ludusavi opened...
anyway, thanks again, you're a ray of sunshine ♥
