### ISSUE TITLE
Inscryption not backed up, even though it should be

### ISSUE THREAD

**Issue by Destroy666x** [mtkennerly/ludusavi-playnite#84]
Not sure if a report for Ludusavi or the Playnite plugin or maybe Playnite itself, but reporting here just in case. Backup is not created for this game and there's notification that nothing to back up was found.

I got Inscryption installed from Epic. According to https://www.pcgamingwiki.com/wiki/Inscryption, the path should be `<path-to-game>\SaveFile.gwsave`. I do have a `SaveFile.gwsave` in `D:\Games\Epic Games\InscryptionWkwPQ`. Playnite also correctly opens `D:\Games\Epic Games\InscryptionWkwPQ` as the installation path.

I'm using latest Playnite, up-to-date plugin and Ludusavi 0.24.3 from choco.

**Comment by mtkennerly** [comment]
Hi! It looks like the issue is that the manifest only had the Steam folder name (`Inscryption`), but not the Epic folder name (`InscryptionWkwPQ`). I've added it to the manifest: https://github.com/mtkennerly/ludusavi-manifest/commit/d8682f139e23b8e4f4211512b5964176e72b406b . You can try it out now by opening Ludusavi, going to the "other" screen, and clicking the refresh icon in the manifest section :)

Also, if you haven't already, make sure that there's an Epic root configured in Ludusavi pointing to `D:\Games\Epic Games`.

**Comment by Destroy666x** [comment]
Thanks, that was quick! It worked fine.
